version: '3.8'
services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  redis:
    container_name: "redis"
    image: redis:3.2
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASS=redis
